steps:
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args:
      - -c
      - |
        docker build -t northamerica-south1-docker.pkg.dev/micrservicesnestjs/lacaja/orders-ms -f dockerfile.prod --platform=linux/amd64 --build-arg ORDERS_DATABASE_URL=$$DATABASE_URL .
    secretEnv: ['DATABASE_URL']

  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'push',
        'northamerica-south1-docker.pkg.dev/micrservicesnestjs/lacaja/orders-ms',
      ]

availableSecrets:
  secretManager:
    - versionName: projects/1097268695783/secrets/ORDERS_DATABASE_URL/versions/1
      env: 'DATABASE_URL'
options:
  logging: CLOUD_LOGGING_ONLY
