version: '3'

services:
  orders-db:
    container_name: orders_database
    image: postgres:16.1-alpine3.19
    restart: always
    volumes:
      - ./postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=p3dr0123
      - POSTGRES_DB=ordersdb
